#!/bin/bash

sudo apt update
sudo apt install smlnj

# Set permissions
chmod +x ./test
chmod +x ./test-compile

# Get python path
PYTHON_PATH=$(which python3)

# Install python dependencies
$PYTHON_PATH -m pip install -r requirements.txt

echo "Set lectura credentials in .env file"
echo -e "\nInstallation complete"
