#!/bin/bash

sudo apt update
sudo apt install smlnj

# Set permissions
chmod +x ./test
chmod +x ./test-compile
chmod +x ./connect-lectura
chmod +x ./submit-lectura
chmod +x ./start-wiki

# Get python path
PYTHON_PATH=$(which python3)

# Install python dependencies
$PYTHON_PATH -m pip install -r requirements.txt

echo -e "Set lectura credentials in .env file\nSee .env.example for reference"
echo -e "\nInstallation complete"
