name: Run SML/NJ Custom Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SML#
      run: |
        sudo apt-get update
        sudo apt-get install smlnj  # Install SML/NJ

    - name: Run SML tests
      run: |
        chmod +x test
        ./test false

